import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddItemsModal from "@/components/AddItemsModal";
import { Toaster } from "react-hot-toast";
import PaymentModal from "@/components/PaymentModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Billing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "max-h-screen overflow-y-hidden")}>
        <Header />
        {children}
        <AddItemsModal />
        <PaymentModal />
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
